name: Auto label

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request_target

jobs:
  label:
    runs-on: ubuntu-20.04
    steps:
      - name: Auto Label
        uses: actions/labeler@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e # tag=v4.0.1
        with:
          configuration-path: .github/auto-label.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
