name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - labels/**/*.yml
      - .github/workflows/sync-labels.yml

  schedule:
    # Checkout for updates daily at midnight
    - cron: '0 0 * * */7'
  
  workflow_dispatch:

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get-core-configs:
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.filelist.outputs.files }}
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Get Core label configs
      id: filelist
      uses: the-coding-turtle/ga-file-list@930f732cb017908f0c43868fb6ce01b9549c2c5e # tag=v0.4.1
      with:
        directory: "labels/core"
        file_extension: "yml"

  sync-core-labels:
    needs: get-core-configs
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: ${{fromJson(needs.get-core-configs.outputs.configs)}}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Sync ${{ matrix.config }} labels
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: labels/core/${{ matrix.config }}
          prune: false

  sync-nx-labels:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Sync Labels
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: labels/nx.yml
          prune: false
